import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
padding = { x = 0, y = 0 }

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "VictorMono Nerd Font"
bold.style = "Bold"
italic.family = "VictorMono Nerd Font"
italic.style = "Italic"
bold_italic.family = "VictorMono Nerd Font"
bold_italic.style = "Bold Italic"
size = 14.0
offset = { x = 0, y = 4 }

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true
