# Github Dark Colorblind Theme for Yazi - Improved Contrast

[mgr]
cwd = { fg = "#79c0ff", bold = true }
hovered = { bg = "#1f2428", bold = true }
preview_hovered = { bg = "#1f2428", bold = true }
find = { fg = "#f0f6fc", bg = "#2d333b", bold = true }
find_keyword = { fg = "#fdcc59", bg = "#2d333b", bold = true, italic = true }
find_position = { fg = "#bc8cff", bg = "#2d333b" }
marker_selected = { fg = "#fdcc59", bg = "#2d333b", bold = true }
marker_copied = { fg = "#79c0ff", bg = "#1f2428", bold = true }
marker_cut = { fg = "#ff7b72", bg = "#1f2428", bold = true }
tab_active = { fg = "#f0f6fc", bg = "#2d333b", bold = true }
tab_inactive = { fg = "#8b949e", bg = "#161b22" }
tab_width = 2
count_copied = { fg = "#0d1117", bg = "#79c0ff", bold = true }
count_cut = { fg = "#0d1117", bg = "#ff7b72", bold = true }
count_selected = { fg = "#0d1117", bg = "#fdcc59", bold = true }
border_symbol = "│"
border_style = { fg = "#484f58" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#484f58", bg = "#161b22" }

mode_normal = { fg = "#0d1117", bg = "#79c0ff", bold = true }
mode_select = { fg = "#0d1117", bg = "#bc8cff", bold = true }
mode_unset  = { fg = "#0d1117", bg = "#fdcc59", bold = true }

progress_label  = { fg = "#f0f6fc", bold = true }
progress_normal = { fg = "#79c0ff", bg = "#2d333b" }
progress_error  = { fg = "#ff7b72", bg = "#2d333b" }

permissions_t = { fg = "#79c0ff", bold = true }
permissions_r = { fg = "#fdcc59", bold = true }
permissions_w = { fg = "#ff7b72", bold = true }
permissions_x = { fg = "#7ee787", bold = true }
permissions_s = { fg = "#c9d1d9", bold = true }

[input]
border   = { fg = "#79c0ff" }
title    = { fg = "#f0f6fc", bold = true }
value    = { fg = "#c9d1d9" }
selected = { bg = "#2d333b", bold = true }

[select]
border   = { fg = "#79c0ff" }
active   = { fg = "#bc8cff", bold = true }
inactive = { fg = "#8b949e" }

[tasks]
border  = { fg = "#79c0ff" }
title   = { fg = "#f0f6fc", bold = true }
hovered = { bg = "#2d333b", underline = true }

[which]
mask            = { bg = "#161b22" }
cand            = { fg = "#79c0ff", bold = true }
rest            = { fg = "#8b949e" }
desc            = { fg = "#bc8cff" }
separator       = "  "
separator_style = { fg = "#484f58" }

[help]
on      = { fg = "#bc8cff", bold = true }
exec    = { fg = "#79c0ff", bold = true }
desc    = { fg = "#c9d1d9" }
hovered = { bg = "#2d333b", bold = true }
footer  = { fg = "#f0f6fc", bg = "#161b22", bold = true }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#7ee787" },

	# Videos
	{ mime = "video/*", fg = "#fdcc59" },
	{ mime = "audio/*", fg = "#fdcc59" },

	# Archives
	{ mime = "application/zip",             fg = "#bc8cff" },
	{ mime = "application/gzip",            fg = "#bc8cff" },
	{ mime = "application/x-tar",           fg = "#bc8cff" },
	{ mime = "application/x-bzip",          fg = "#bc8cff" },
	{ mime = "application/x-bzip2",         fg = "#bc8cff" },
	{ mime = "application/x-7z-compressed", fg = "#bc8cff" },
	{ mime = "application/x-rar",           fg = "#bc8cff" },
	
	# Documents
	{ mime = "application/pdf", fg = "#ff7b72" },
	{ mime = "application/msword", fg = "#79c0ff" },
	{ mime = "application/vnd.*", fg = "#79c0ff" },

	# Fallback
	{ name = "*", fg = "#c9d1d9" },
	{ name = "*/", fg = "#79c0ff", bold = true }
]

[icon]
rules = [
	# Programming
	{ name = "*.c",    text = "", fg = "#599eff" },
	{ name = "*.cpp",  text = "", fg = "#f34b7d" },
	{ name = "*.h",    text = "", fg = "#599eff" },
	{ name = "*.hpp",  text = "", fg = "#f34b7d" },
	{ name = "*.rs",   text = "", fg = "#dea584" },
	{ name = "*.go",   text = "", fg = "#00add8" },
	{ name = "*.py",   text = "", fg = "#ffdd54" },
	{ name = "*.js",   text = "", fg = "#f1e05a" },
	{ name = "*.ts",   text = "", fg = "#2b7489" },
	{ name = "*.tsx",  text = "", fg = "#2b7489" },
	{ name = "*.jsx",  text = "", fg = "#79c0ff" },
	{ name = "*.rb",   text = "", fg = "#cc342d" },
	{ name = "*.php",  text = "", fg = "#a074c4" },
	{ name = "*.java", text = "", fg = "#cc7832" },
	{ name = "*.sh",   text = "", fg = "#4eaa25" },
	{ name = "*.fish", text = "", fg = "#4eaa25" },
	{ name = "*.bash", text = "", fg = "#4eaa25" },
	{ name = "*.zsh",  text = "", fg = "#4eaa25" },
	{ name = "*.ksh",  text = "", fg = "#4eaa25" },
	{ name = "*.csh",  text = "", fg = "#4eaa25" },
	{ name = "*.awk",  text = "", fg = "#4eaa25" },
	{ name = "*.ps1",  text = "", fg = "#4eaa25" },
	{ name = "*.lua",  text = "", fg = "#000080" },
	{ name = "*.vim",  text = "", fg = "#019833" },
	{ name = "*.diff", text = "", fg = "#ff7b72" },
	{ name = "*.html", text = "", fg = "#e34c26" },
	{ name = "*.xml",  text = "", fg = "#e34c26" },
	{ name = "*.css",  text = "", fg = "#563d7c" },
	{ name = "*.scss", text = "", fg = "#f55385" },
	{ name = "*.json", text = "", fg = "#cbcb41" },
	{ name = "*.toml", text = "", fg = "#9c4221" },
	{ name = "*.yaml", text = "", fg = "#cb171e" },
	{ name = "*.yml",  text = "", fg = "#cb171e" },
	{ name = "*.ini",  text = "", fg = "#6d8086" },
	{ name = "*.conf", text = "", fg = "#6d8086" },

	# Text
	{ name = "*.txt", text = "", fg = "#c9d1d9" },
	{ name = "*.md",  text = "", fg = "#083fa1" },

	# Archives
	{ name = "*.zip", text = "", fg = "#bc8cff" },
	{ name = "*.tar", text = "", fg = "#bc8cff" },
	{ name = "*.gz",  text = "", fg = "#bc8cff" },
	{ name = "*.7z",  text = "", fg = "#bc8cff" },
	{ name = "*.bz2", text = "", fg = "#bc8cff" },
	{ name = "*.xz",  text = "", fg = "#bc8cff" },

	# Images
	{ name = "*.jpg",  text = "", fg = "#7ee787" },
	{ name = "*.jpeg", text = "", fg = "#7ee787" },
	{ name = "*.png",  text = "", fg = "#7ee787" },
	{ name = "*.gif",  text = "", fg = "#7ee787" },
	{ name = "*.webp", text = "", fg = "#7ee787" },
	{ name = "*.avif", text = "", fg = "#7ee787" },
	{ name = "*.bmp",  text = "", fg = "#7ee787" },
	{ name = "*.ico",  text = "", fg = "#7ee787" },
	{ name = "*.svg",  text = "", fg = "#7ee787" },

	# Videos
	{ name = "*.mp4",  text = "", fg = "#fdcc59" },
	{ name = "*.mkv",  text = "", fg = "#fdcc59" },
	{ name = "*.avi",  text = "", fg = "#fdcc59" },
	{ name = "*.mov",  text = "", fg = "#fdcc59" },
	{ name = "*.webm", text = "", fg = "#fdcc59" },

	# Audio
	{ name = "*.mp3",  text = "", fg = "#fdcc59" },
	{ name = "*.flac", text = "", fg = "#fdcc59" },
	{ name = "*.wav",  text = "", fg = "#fdcc59" },
	{ name = "*.aac",  text = "", fg = "#fdcc59" },
	{ name = "*.ogg",  text = "", fg = "#fdcc59" },
	{ name = "*.m4a",  text = "", fg = "#fdcc59" },
	{ name = "*.opus", text = "", fg = "#fdcc59" },

	# Documents
	{ name = "*.pdf", text = "", fg = "#ff7b72" },
	{ name = "*.doc", text = "", fg = "#79c0ff" },
	{ name = "*.docx", text = "", fg = "#79c0ff" },
	{ name = "*.xls", text = "", fg = "#1e7e34" },
	{ name = "*.xlsx", text = "", fg = "#1e7e34" },
	{ name = "*.ppt", text = "", fg = "#d14524" },
	{ name = "*.pptx", text = "", fg = "#d14524" },

	# Default
	{ name = "*",  text = "", fg = "#c9d1d9" },
	{ name = "*/", text = "", fg = "#79c0ff" },
]