return { 
  -- {
  --   'mfussenegger/nvim-jdtls',
  --   config = function()
  --     local config = {
  --         cmd = {'jdtls'},
  --         root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
  --     }
  --     require('jdtls').start_or_attach(config)
  --   end,
  -- }
  -- {
  --   'nvim-java/nvim-java',
  --   config = function()
  --     require('java').setup({
  --       -- your configuration comes here
  --       -- or leave it empty to use the default settings
  --       -- refer to the configuration section below
  --     })
  --   end,
  -- }
}
