model = "gpt-5-codex"
[projects."/Users/brendanmullins/Projects"]
trust_level = "trusted"

[projects."/Users/brendanmullins/Projects/next-sanity"]
trust_level = "trusted"

[projects."/Users/brendanmullins/Projects/eco-construct"]
trust_level = "trusted"

[projects."/Users/brendanmullins/dotfiles"]
trust_level = "trusted"

[projects."/Users/brendanmullins/Projects/aitest/strem_process_anchor"]
trust_level = "trusted"

[projects."/Users/brendanmullins/Projects/mcpm"]
trust_level = "trusted"

[mcp_servers.web-search]
command = "mcpm"
args = ["--server=web-search", "--agent=codex"]

[mcp_servers.atlassian]
command = "mcpm"
args = ["--server=mcp-atlassian", "--agent=codex"]

[mcp_servers.playwright]
command = "mcpm"
args = ["--server=playwright", "--agent=codex"]

[mcp_servers.magic]
command = "mcpm"
args = ["--server=@21st-dev/magic", "--agent=codex"]
